### ISSUE TITLE
GitLab is hosted on Azure

### ISSUE THREAD

**Issue by davidgarland** [AGausmann/github-no-more#1]
Which is run by Microsoft.

If you seriously think they're spying on peoples private repos then it's not as though moving to GitLab will help, though im doubtful Microsoft cares about any enthusiast projects.

**Comment by AGausmann** [comment]
You have a point, but that is a different situation. GitHub is now being _acquired_ by Microsoft, which means they have a say in how everything goes, including what goes into their proprietary Enterprise servers. GitLab's software is not influenced by Microsoft in the same way; while their SaaS servers may be hosted by them, there is still the option to run the free/libre GitLab Community Edition software on your own machine.

I'm not concerned about spying or any other conspiracy like that, I'm concerned about supporting both parties' decisions: Microsoft's decision to suspiciously reach into and influence the FLOSS communites while the vast majority of their software remains proprietary, and GitHub's decision to work with Microsoft while they still haven't regained my trust. [Embrace, Extend, Extinguish](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish) is a well-known tactic that I fear Microsoft may still be using, and I want to separate myself from them as much as possible until they can prove otherwise.

**Comment by davidgarland** [comment]
I don't think there's any way for them to "prove otherwise", though-- and lots of Microsoft's software being proprietary is more so for the goal of making profit than hiding information, so far as I can tell.

I know they've been hostile towards FLOSS in the past, but they are also notably under new leadership now. Also notably if they did intentionally hurt GitHub's usability there are already alternatives like GitLab and such sitting around (which I have learned is now moving to Google hosting soon, though I doubt that's truly any better) which people would flock to, and Microsoft would receive backlash for it.

Another possibility to consider is that they may leave GitHub intact for the most part, allowing the previous facilities to continue semi-autonomous operation like they did when they acquired Mojang-- the core team there is still the same, even if Microsoft now gets the final say in any decision should they want to interject.

I do agree that why they bought GitHub is dubious, as it doesn't seem like a particularly profitable thing to own-- if anything I'd expect GitHub to be actively losing money, unless I grossly underestimate the amount of private repos. You are right to be suspicious of this, but I'm not sure it warrants a jerk reaction like a full migration to GitLab. 

Additionally there's no saying GitLab wouldn't do the exact same thing given the same proposition-- [passive aggressive](https://about.gitlab.com/2018/06/03/microsoft-acquires-github/) posts to attempt to scare users over seem to imply they are driven by the same corporate greed as any other given company; just because they support FLOSS doesn't mean they are exempt from this rule. As an extension of this, the enterprise edition of GitLab isn't a truly "free" product in either sense of the word, as it requires payment to use-- at the end of the day GitLab is still a company.
